language: nix
sudo: false
cache:
  directories:
  - "$HOME/nix.store"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- sudo mkdir -p /etc/nix
# make sure no browser is left over that can disturb the karma tests (nix-shell provides the browsers!)
- sudo apt-get remove google-chrome-stable -y
- sudo apt-get remove chromium-browser -y
- echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
- echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null
before_cache:
- mkdir -p $HOME/nix.store
- nix copy --to file://$HOME/nix.store -f default.nix buildInputs

env:
  global:
    - # Environment variables for NPM version patch for GitHub user
    - secure: "C1mGKsF71ALfMEwi/dUjuuTHqFqHVSy65rLtQN+CK4oSQo3K5YxFKIWboMPi2rAS3C5DaTSmAyOUKUb7iTUG6v43Hp3zeWSW3sNVEerlwOXPOMmBGkPbMIKkgjDkyw/AbogixqDCBnDoAZhCRQ8dAWrGf1qUHLexJE0NGEgjl2xVjnPJsexIKYQIRzUmPzlVkew2mfLxm5u1y2/i3Qu/sgIHcHV/zOPCmLLYd0JhKrMbUGq4ZO7zGIYNm/ixWWXI8uV9Fb8BGuVoBxP91vcx2nNh6IpZDtcx0ZUSwcio7hzVvOgmHLv+wnEzczJVj0PXDEeH4N0FcuP/pdT4kbmrfRWHgbva8HUAO8uVqYdjdBMWemzxVGWK36dM09crLbFo3lRC4XdWFOIoEGrrThld97bXZajqDyOBqHMLsFn/CzNO6NZErFWXGJ0dlpqvqczTytVWlSzcqbIn3DVVXM0vR6c/lB60JELKmkoPIMjpz11Z8qi3ddJG7BtPBRr21iVoOHlQ7lkr0sOSLDlSRQxNe+RbIrq75/FVN69KhqS7n/HnRJcDOiigNxmz8JGE4p80z+VlKrKnf61KOpFSltijnXGxT8G4xQ0mlsFiQTXg78e3yNtR06PodaATY0PHQ7j1WYE+VX+84dt5kcJTjBZI9OfxtCH4TjMm3w/d4Frc/qo="
    - secure: "jnX4d63Atw6zceYdLLJ+gX6MYo5Wrk/mqtbqrrPpmIQ3W3gobfk5y0IzI79+S5l/4AUtqYAx2nHwKv/s9P+zkN8mTYbH8PVlWmr6J2hB4lxK8vjUxR5yVl5qykeWcpU0Ek4OFR55hqHEMELiGrkefeY8ftGuB9XXXpgkvqB7rnH/aEHUKnBvfTECcUzWbn7aYVzpbnurPVez5E4Iug3QzHEkqLmyQn/kRhvzmUOYgC4BsvHNpUoruZCTtXRynoqSc4zlLcwI1T+lA0QnBW5UQUsWkWoPU9/Q9TRzbYBL2D3mI0LqzSUxK2XyfdeSqlSZKwZwM/ADkIwm3G1Q5pl12mymQJoFUOll002y2ldxc4JXjg0Fn6n38CuDFEDFrXD4SD93x8tDnhq1O3BOc63zOUmqQMoCUBlIWMEO7O+DcFMhLML7sKUmSzaqdG5rjfeX78qclBMru112ud//xkAqRrFMlOxKXsagC7ZH2nVlthNApOzV9FVzUwq5FVNVZWyG40+GJ4zgLn8hm3fVch6qwdT+DtEp1HLqNsP0u8v8ZMxI9ZX4MLnFTmwy99558AiO04iSj4Xsy+PJVbJpDQftEgYFqwqxI1K0CS9nd6bUPjE5MchZBBr9AdZTmPJtV5ndpD3FP7pugKEE46OrJC0Zm0A4CG01FjMSIHJITzP8tnA="
    - NIXPKGS_ALLOW_UNFREE: 1

  matrix:
    - FIREFOX_VERSION="latest"
    - FIREFOX_VERSION="60-esr"

install:
- nix-shell shell-${FIREFOX_VERSION}.nix --command "yarn install"
script:
- nix-shell shell-${FIREFOX_VERSION}.nix --command "firefox --version"
- nix-shell shell-${FIREFOX_VERSION}.nix --command "google-chrome --version"
- nix-shell shell-${FIREFOX_VERSION}.nix --command "yarn run lint"
- nix-shell shell-${FIREFOX_VERSION}.nix --command "xvfb-run --server-args=\"-ac -screen 0 1920x1080x16\" yarn run test:once"
- nix-shell shell-${FIREFOX_VERSION}.nix --command "xvfb-run --server-args=\"-ac -screen 0 1920x1080x16\" yarn run e2e"
- nix-shell shell-${FIREFOX_VERSION}.nix --command "yarn run packagr"

after_success:
# Autoincrement of patch level version:
# Tag the repo with a new patch level version tag, if this build is done on
#     'FIREFOX_VERSION = latest' and (only one of the matrix-builds is relevant)
#     this is not a pull request and (pull requests themselves should not autoincrement)
#     this branch is the master branch and (only builds on master are relevant)
#     there is no tag given (if a tag is alread given, this one will be published and should not again be tagged!)
- 'if [ "$FIREFOX_VERSION" = "latest" -a "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_TAG" = "" ]; then wget https://github.com/test-editor/commons-build-automation/raw/master/travis/deploy/tag_with_new_patch_version.sh; nix-shell shell-${FIREFOX_VERSION}.nix --command  "bash tag_with_new_patch_version.sh"; fi'
before_deploy:
- touch .npmignore
- cd dist/
deploy:
  skip_cleanup: true
  provider: npm
  email: testeditor.eng@gmail.com
  api_key:
    secure: "ZvSCTpq82AzdBLvZy7y0YckRP8MOGGv9GQS66DMwR3Nslo2W5+DcmYpdRth7jSA1DZ3FIM1ogANLEGuoxqcAOwkC61LsI30R8gINx2UDIvF/duJo8XRp9bXRvTZ1VgjXa3TQgCtiYyRSYUKU4K+pzoPLIvf+m+AOvLNN3ot04Tr3IS+vplaLLcSOLEQp7FOnGsW7qVpF/C8UQK29REpra3ynNs80SmPl7W41wtiALN4Le/0TvaROJqGoiXmcxEXK9QBW4lMbNwSiMkzNMJ/YrxwKjUl5V7Jt3soM+P/MSBMph+GXLlJTtMMayKUYMIq2avqN/YL3jetuoaY5lh1mEhsEe7LJkd4Erbrsa3gq7c9bu5K7YRqmb1vceJQDyUg6NOARpmG7RpEN/81eModwfd4ktSVsA1GZz7osSDZ1bbDEPgZGa8Hftk5Nk38xG5bOo8vG2KU0ss4EiLZYzuwsQptN9JEBr/iLjhJsBjxRe0HzwTHIYji0YW4RyLnxr6Y9oKYT0DblLrgVnV0pKCpL65QV7ncLSu7aOcsA3cnNsfVuqKPl3z5SyigQ7fZk4q4M7ov36SnbJDDj5ISRw43ygvy3F3lbCwuT27ZbBshPplSQScpEv68P/MhktSewbAG+figGVaykfHVqA+n9dEXFoP/g4lTjblW0ZBF7s1KAP4o="
  on:
    condition: "$FIREFOX_VERSION = latest"
    tags: true
    repo: test-editor/web-test-navigator
